### ISSUE TITLE
List of files does not refresh after a commit or commit/push with TortoiseGit

### ISSUE THREAD

**Issue by astrohart** [vinsworldcom/nppGitSCM#11]
I am utilizing Notepad++ 8.4.1 (64-bit) on Windows 10 Pro with all the latest updates installed.  I am utilizing release 1.4.7.1 of this plugin.

**The Issue**

As a user, once I do a commit to my local repo and push the changes to the remote, I expect the docking panel to remove the file(s) in question from the list of modified files.  It does not; the entries remain.

**To Reproduce**

1. Open a file that is contained in a local Git repo that is associated with a remote, in N++.
2. Click the **Plugins** menu, point to **GitSCM**, and then ensure a check mark is next to the command **Git Docking Panel**, as shown in **Figure 1.**
3. Make sure there is a check mark in the **Use TortoiseGit** checkbox in the docking panel.
4. Make a change to the file and save it.
5. Click the **Commit** button.  TortoiseGit displays a window for you to enter the commit message.  If your repository requires it, type a commit message, and then, In TortoiseGit, click the **Commit and Push** button.
6. Dismiss the **Commit and Push** dialog displayed by TortoiseGit once the application has completed the operation.
7. The file remains listed as "modified" in the docking panel.  This is the issue.

![image](https://user-images.githubusercontent.com/8261875/170850065-81c6c599-6c35-48b6-bc02-cd108d05de7d.png)
**Figure 1.**  _Opening the Git Docking Panel._

**Comment by vinsworldcom** [comment]
There is not a way for me to get a notification from Tortoise that a change has occurred - I can only get Notepad++ or Scintilla notifications.  If you click in the panel after a push or change the current tab after a push, then the panel will update.

**Comment by astrohart** [comment]
Is the extension written in, e.g. Managed C++/CLI (that means, you can access the .NET Framework in your code)?
  
  
   
  
  
   If so, then you can use `System.IO.FileSystemWatcher` to watch the folder.
  
  
   
  
  
   If not, then how about simply polling the folder, e.g, every 5 seconds while the file remains open?
  
  
   
  
  
   I've seen the modified file icon go away, say, after the file is closed in Notepad++.
  
  
   
  
  
   Brian
  
  
   
    On 05/31/2022 8:09 AM Vince ***@***.***> wrote:
   
   
    
   
   
    
   
   
   There is not a way for me to get a notification from Tortoise that a change has occurred - I can only get Notepad++ or Scintilla notifications. If you click in the panel after a push or change the current tab after a push, then the panel will update.

**Comment by astrohart** [comment]
>  If you click in the panel after a push or change the current tab after a push, then the panel will update.

I've tried to click in the panel, and nothing happens when I do that.

There is also `LibGit2Sharp` NuGet package for you to utilize to connect to a local Git repository on the user's hard disk.  This will subscribe you to file-changed notifications.

**Comment by astrohart** [comment]
Link for `System.IO.FileSystemWatcher`:
https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-6.0

Excuse me, for C++ it's `libgit2`:
https://github.com/libgit2/libgit2

**Comment by astrohart** [comment]
Another option is to set up a background worker thread.  I've been looking at the code.  I am highly skilled in C++ but not in programming Notepad++ plugins.  So I am hard-pressed to help out with pull requests.

But what I will be willing to do is to fork the repository and if I get any bright ideas, I will let you know.

**Comment by astrohart** [comment]
Another idea that just came to me: use GitSCM or tortoise or whatever to do a commit, and wait on the spawned process to exit using the `WaitForSingleObject` API on the handle that `CreateProcess` returns.  Then, do a `git status` on the folder that the active file is sitting in, to see if there are changes.

Or, poll every 5 seconds and just call a `git status` on the folder the active file is sitting in, and update the panel as need be.

**Comment by vinsworldcom** [comment]
@astrohart I like the monitoring solutions, but don't have the C++ chops to implement.  The 5-second polling while it would probably work, I think would be an unnecessary drain on system resources running a command over and over which 95% of the time would result in no change.

Happy to entertain a pull request from your forked version if you can find a creative solution.

Cheers.
