### ISSUE TITLE
Not working with space(s) in path

### ISSUE THREAD

**Issue by Tabiskabis** [vinsworldcom/nppGitSCM#12]
I've been expecting spaces in path/directory and filenames to work for the last twenty years or so. 
Assuming this to be some odd bug that only happens with my setup, what info do you need?

**Comment by vinsworldcom** [comment]
What version are you using.  This seems fine for me:

![image](https://user-images.githubusercontent.com/9657169/192398347-a99c7276-7850-46bf-b7a2-a1fa841f237d.png)

Cheers.

**Comment by Tabiskabis** [comment]
Notepad 8.4.5 (64-bit), GitSCM 1.4.7.1
When I doubleclick the "M", a cmd pops up and disappears right away.
Pressing the commit button pops up a usesless cmd (screenshot). Its command line is `cmd /d/c ""git" commit  & pause"`
Issuing the same command manually brings up vim as expected
![Screenshot 2022-09-28 141612](https://user-images.githubusercontent.com/23276816/192776303-4e244be1-66cd-47db-b11c-fff97c8601a7.png)

**Comment by vinsworldcom** [comment]
If after double-clicking the `M` it does not move the `I` column, then you haven't actually added anything (`git add ...`) and thus commit-ing (`git commit ...`) will do nothing.

Turning on debug, I can see the issue.  TortoiseGit happily handles spaces in paths/names internally so I don't have to.  Without using TortoiseGit, I need some extra logic to add double-quotes (`"`) around file names.  Current operation:

```
[25620] cmd /d/c ""git" add C:\Users\mvincent\Desktop\New folder\baz"
```

Fix required:

```diff
diff --git a/PluginDefinition.cpp b/PluginDefinition.cpp
index ad9bce8..9617646 100644
--- a/PluginDefinition.cpp
+++ b/PluginDefinition.cpp
@@ -368,7 +368,9 @@ void ExecGitCommand(
         for ( std::vector<std::wstring>::iterator itr = files.begin();
                 itr != files.end(); itr++ )
         {
+            command += TEXT( "\"" );
             command += ( *itr );
+            command += TEXT( "\"" );

             if ( itr != files.end() - 1 )
                 command += TEXT( " " );
```

After fix:

```
[28576] cmd /d/c ""git" add "C:\Users\mvincent\Desktop\New folder\baz" "C:\Users\mvincent\Desktop\New folder\foo""
```

If you know how to manually install, you can try the artifact at:
https://github.com/vinsworldcom/nppGitSCM/actions/runs/3143797401

appropriate for your architecture and let me know if it works.  I did setup a "New Folder" repo on my desktop with some files 'baz' and 'foo' to best emulate your setup and it tested fine this time.  Let me know .. and I'll go ahead with the new version release which has some other fixes as well.

PS: If you'd prefer a pre-compiled pre-release, let me know and I can make that available as well.

Cheers.

**Comment by Tabiskabis** [comment]
Working as expected now, thanks. This ought improve my so far manual workflow 👍

**Comment by Tabiskabis** [comment]
I see a green checkmark in your screenshot. Is that another feature only available with Turtoise, or something entirely else?

**Comment by vinsworldcom** [comment]
The green checkmark in the Notepad++ tab is just using the new icons:

Settings=>Preferences=>General => Alternate Icons

Nothing to do with this plugin :-)

Cheers.

**Comment by Tabiskabis** [comment]
Related: GitSCM does not support UNC paths.
This could be fixed by using `git -C "\\UNC\Path" <command>`
