### ISSUE TITLE
Failed could not launch Git. The filename, directory name, or volume syntax label syntax is incorrect.

### ISSUE THREAD

**Issue by knudvaneeden** [vinsworldcom/nppGitSCM#13]
I installed the latest 64 bit version of Notepad++ version 8.4.7
Also the latest 64 bit .exe installer for Git-SCM version 2.38.1.windows.1

Then whatever I try from within Notepad++ regarding the Git-SCM plugin options
it failes with this error message:

'Failed could not launch Git. The filename, directory name, or volume syntax label syntax is incorrect.'

Tried:
-Checking if Notepad++ and GIT-Scm are the 64 bits versions
-Running the executale 64 bits installer for GIT-SCM
-Running the portable 64 bits installer for GIT-SCM
-Checking if path to GIT-SCM is in the Microsoft Windows environment variable PATH: yes
-Check if using '/' instead of '\\' (backslash) in the path
-Setting the settings in 'Settings' in the Notepad Git-SCM menu
-Empty path in the 'Settings'
-Run Notepad++ as administrator
-Put double quotes around the path in gitscm.ini
-Put single quote around the path in gitscm.ini
-Disable temporarily the anti-virus program, then restart Notepad++ and try again
-Checked the Git-SCM plug-in source code to see what was used (e.g. 'cmd')
-Both Notepad++ and Git-scm are installed on a USB drive (with drive letter G:)
-Run dbgview.exe to debug
-Checked https://github.com/vinsworldcom/nppGitSCM about how to install
-Checked https://github.com/vinsworldcom/nppGitSCM/issues/2
-Searched Google for e.g. 'Notepad Plugin The filename, directory name, or volume syntax label syntax is incorrect.'
-Restarted the computer
-Installed the latest update from Microsoft Windows

-Note: Running the commands like

  cmd /d/c ""G:\VERSIONCONTROL\GIT\GITSCM\cmd\git-gui" "

 from the command line (doing a copy/paste of this line): Yes, then it works and launches the GIT GUI.
=> So it does *not* work when launched the same command is run out of the Notepad++ menu.

**Comment by vinsworldcom** [comment]
Do you have a file that is in a git repository open in Notepad++?  With Notepad++ just open and no file (i.e., the editing component just has a "new-1" buffer open, then you will get this error when trying to launch Git GUI.  You need to have a file open that is in an actual Git repo.

Cheers.

**Comment by knudvaneeden** [comment]
Hello,
Yes, tested and that works now.
Thankswith friendly greetingsKnud van Eeden
    On Wednesday, November 16, 2022 at 03:36:34 AM GMT+1, Vince ***@***.***> wrote:  
 
 


Do you have a file that is in a git repository open in Notepad++? With Notepad++ just open and no file (i.e., the editing component just has a "new-1" buffer open, then you will get this error when trying to launch Git GUI. You need to have a file open that is in an actual Git repo.

Cheers.

**Comment by vinsworldcom** [comment]
@knudvaneeden it's a shame it doesn't provide a better message or in fact, just launch Git-GUI with the option to create a repo like it does when you run from the command line.  It must be some flags of the CreateProcess() API used to launch from this plugin coupled with error codes from the Git GUI program when no repo is found.

Cheers.

**Comment by knudvaneeden** [comment]
> it's a shame it doesn't provide a better message or in fact, just launch Git-GUI with the option to create a repo like it does when you run from the command line. It must be some flags of the CreateProcess() API used to launch from this plugin coupled with error codes from the Git GUI program when no repo is found.

This a very persisting error (did not go away whatever tried and that were many different attempts), and it does indeed tell nothing about a root cause
(e.g. must be file under GIT control).
It should thus ideally be taken care of by the Notepad++ team (open source) responsibles further.

Otherwise maybe in your C++ plugin there could be additional checks, not sure (maybe the filename or buffer loaded 'new' ,...).
Thanks.

**Comment by vinsworldcom** [comment]
@knudvaneeden have a try with your first scenario with the artifact for your architecture at:
https://github.com/vinsworldcom/nppGitSCM/actions/runs/3481016639

I tried to add a bit more detail to the error message along with allowing GUI execution regardless of file status.

Cheers.

**Comment by knudvaneeden** [comment]
Yes, that works:
It now shows thus:
'Could not launch Git.The filename, directory name, or volume label syntax isincorrect.
Current directory is empty. Is this a 'new-1' file or have you saved it? Is the file in a current git repo directory?
===
> Is this a 'new-1' file or have you saved it?

Note: in my case the filename was 'new-2', so the moregeneral message could be something 'new-...'
> Is the file in a current git repo directory?

Note: I assume that the user would like to do all actions in and from Notepad++ itself. 
But this solution assumes already some Git preparations were done outside of Notepad++. 
In principle all could be done out of Notepad++ itself thus, e.g. creating the repository directory, copying the file into it and then doing an 'add' and possibly 'commit'.



    On Wednesday, November 16, 2022 at 05:12:27 PM GMT+1, Vince ***@***.***> wrote:  
 
 


@knudvaneeden have a try with your first scenario with the artifact for your architecture at:
https://github.com/vinsworldcom/nppGitSCM/actions/runs/3481016639

I tried to add a bit more detail to the error message along with allowing GUI execution regardless of file status.

Cheers.

**Comment by vinsworldcom** [comment]
Closed with f91f0aa8f64ef28ca5dd8a95b264143cabc3cd93
