### ISSUE TITLE
[FR] Folder as Workspace integration

### ISSUE THREAD

**Issue by sdasda7777** [vinsworldcom/nppGitSCM#18]
Hi, I know this will most likely be a lot of work, and I'm not even sure if Notepad++ has the necessary API for this, but if possible, would you consider adding integration with Folder as Workspace?

Specifically, it would be really nice if you were able to graphically show current status of individual files/folders (when the given folder is a git directory), and provide git commands from a right click menu in the Folder as Workspace panel.

This is loosely what I have in mind for the current status. Mainly it would be nice if you could easily see any uncommited changes. (pictured is Windows explorer with TortoiseGit):

![image](https://github.com/vinsworldcom/nppGitSCM/assets/17746796/1c004a57-ceb3-4b33-93f0-e6226c6eb386)

This is loosely what I have in mind for the commands. Mainly it would be nice if you could just select multiple files and `add`/`stash`/`restore` them at the same time. (pictured is IntelliJ Idea):

![image](https://github.com/vinsworldcom/nppGitSCM/assets/17746796/749d4530-fced-479a-86f0-319af5d30deb)

**Comment by vinsworldcom** [comment]
Not possible with Notepad++ API.  If you have Tortoise Git installed, use this plugin and have the Explorer plugin installed (I use https://github.com/funap/npp-explorer-plugin version), then you can see the icons in the Explorer plugin panel and have the Tortoise Git right-click context menu off the right-click menu in Explorer plugin panel.

Cheers.
