### ISSUE TITLE
Commit/push/pull doesn't work

### ISSUE THREAD

**Issue by Totenstarre** [vinsworldcom/nppGitSCM#3]
Hey

So I'm having some trouble getting these functions working.

I have read and followed your suggestions in the other issue but i just can't get it working.

If i click the first "git" icon i get the Git GUI open and it seems to work ok from there.

GitK icon returns a grey box with "Cannot find a git directory here".

Git prompt returns the windows powershell in the right directory and if i type "git status" it works fine.

The Pull, Status, Commit, Log and Blame returns "fatal: not a git repository (or any of the parent directories): .git
Press any key to continue . . ."

Add, Unstage and Restore returns a flash of CMD and then nothing happens.

All of this is without TortoiseGit activated (it is installed though).

If i activate TortoiseGit and click Pull, Status, Commit or push it returns "No Working directory found".

Default Directory i set to "Follow current document"

I have tried reinstalling Git and npp but that didn't help.

I hope i have supplied enough info to start out with.

**Comment by vinsworldcom** [comment]
My guess is that you're not in the directory you think you are or the Git plugin is not in the directory you think it is.  Provided you have the latest version:

1. Close Notepad++
2. Use a DIFFERENT TEXT EDITOR (like Windows notepad.exe) to manually edit the config file `$(NPP_DIR)/plugins/config/GitSDM.ini` to include the line:

```
Debug=1
```

3. Re-open Notepad++

You will also need to get [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) and run it.

You can use the "Include" filter of "*git*" if you are getting too many messages too fast.

Then do your tests again.  The commands the plugin is running will be sent to the DebugViewer window:

![image](https://user-images.githubusercontent.com/9657169/101204523-59f28080-363a-11eb-8beb-d5622c35a73e.png)

Notice no directories are provided in most commands so it is important that you have Notepad++ set to follow current directory and you have a file **open and active** in Notepad++ that is in the directory you are trying to access Git from.

Cheers.

**Comment by Totenstarre** [comment]
Hi

Thanks for answering so quickly.

The output of DebugView:

![image](https://user-images.githubusercontent.com/35933693/101282175-c654b780-37d3-11eb-81f9-2897f015b5df.png)

So the Add function gets the right directory but commit doesn't?

At line 12 after "commit" and before "&", there is an extra space like the directory "variable" output is missing.

Is it getting that from what ever is saved when you press add?

I's it because I'm doing something wrong?

I have installed the latest release of npp, git and GitSCM.

**Comment by Totenstarre** [comment]
The panel looks like this btw.

So i guess some of the functions are working

![image](https://user-images.githubusercontent.com/35933693/101282541-1f254f80-37d6-11eb-907c-2c9784f27c31.png)

**Comment by vinsworldcom** [comment]
Add gets a filename(s) because yyour can't just 'git add'.  Commit does not
need a filename or directory because you just 'git commit' from a directory
in the repo and it works.  That's why you need follow current file enabled
AND a file in the repo opened and active in Notepad++.

Also note from your image, commit won't do anything as you have nothing to
commit.  You have a file modified in the working space (w) but you have not
'git add' it to index (I).

Cheers.

**Comment by Totenstarre** [comment]
Allright.

I'm probably doing something wrong.

Follow current file is enabled.

There's a file open and active in the repo.

After editing and saving the file, i click Add, but the M doesn't shift from W to I.

After fiddling around with the different commands i right click on another file and click open, it opens that file and suddently both M's goes from W to I.

So... i click commit but still... 

![image](https://user-images.githubusercontent.com/35933693/101283409-6f061580-37da-11eb-99fc-ccb799729ea5.png)

**Comment by vinsworldcom** [comment]
Right-click on the roger-class.php tab and close to open a command prompt.
Type 'git commit' from that command prompt.  Does it work?

Cheers

**Comment by Totenstarre** [comment]
Yeah that seems to work, forgot to add first so i did that in cmd.
![image](https://user-images.githubusercontent.com/35933693/101283662-23ed0200-37dc-11eb-9e91-791979c4fade.png)

and after i typed in the commit line, saved and closed the window
![image](https://user-images.githubusercontent.com/35933693/101283715-83e3a880-37dc-11eb-87fd-214528a97fac.png)

**Comment by vinsworldcom** [comment]
My guess is that you have command prompt set to start in a specific
directory.

**Comment by Totenstarre** [comment]
It seems to be set to my home dir.

**Comment by vinsworldcom** [comment]
If you remove that startup directory from command prompt I think it should
work.

Cheers

**Comment by mlehenb** [comment]
I have this same issue and could not come up with any environment changes to get it to work. I tweaked launchGit() to set the directory on the CreateProcess call and that seems to work for me. I can do a pull request if you are interested.

**Comment by vinsworldcom** [comment]
> I have this same issue and could not come up with any environment changes to get it to work. I tweaked launchGit() to set the directory on the CreateProcess call and that seems to work for me. I can do a pull request if you are interested.

Yes, please feel free.  I was tinkering with doing that as well myself for the next version so I could probably incorporate that if it indeed works as you've tested.

Cheers.

**Comment by vinsworldcom** [comment]
Please try [1.4.4.3](https://github.com/vinsworldcom/nppGitSCM/releases/tag/1.4.4.3)

**Comment by mlehenb** [comment]
Thanks! This works for me.

**Comment by Totenstarre** [comment]
It works for me too, thank you very much :)

**Comment by vinsworldcom** [comment]
No worries - sorry it took so long to sort.  Thanks much @mlehenb for the elegant solution!
