### ISSUE TITLE
Getting fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by FStapenhorst** [vinsworldcom/nppGitSCM#5]
I click on "Status" button in the Docking Panel and I get:
<img width="1079" alt="error" src="https://user-images.githubusercontent.com/34714546/148815905-f7b73620-b3d7-4023-88cb-cd14bffb970d.png">

Looking at the command line (using Process Explorer) shows:
<img width="431" alt="cmdline" src="https://user-images.githubusercontent.com/34714546/148816755-9c49d80e-0817-4bfb-81cc-18e80ac85e0c.png">

Settings:
<img width="436" alt="setting2" src="https://user-images.githubusercontent.com/34714546/148816733-7ff6db40-85a0-4778-9036-d5ee9a367b4b.png">

Running the command manually in the correct folder works:
<img width="678" alt="manual" src="https://user-images.githubusercontent.com/34714546/148817055-c4f0f994-d037-4885-9353-4ed2a035af5f.png">

Looks like the work folder of the current file is not set when calling cmd.exe

What can I do to make this work?

**Environment**
Notepad ++ v 8.1.9.3 (64bit)
Git Version (git is in the path):
```
C:\>git --version
git version 2.33.0.windows.2
```
Notepad ++ setting "Follow current document" is configured
<img width="1098" alt="setting" src="https://user-images.githubusercontent.com/34714546/148815779-561dc6b1-b9d4-413b-a69d-8f8c8b47a2cc.png">

**Comment by pschneider1968** [comment]
Coincidentally, I just had the same issue (with Plugin version 1.4.4.2, installed by N++ plugin manager).
I replaced the GitSCM.dll in my "C:\Program Files (x86)\Notepad++\plugins\GitSCM" folder with that from the release page, version 1.4.5.1, and that fixed the issue for me. Both the Git CMD line tools and the TortoiseGit features (if enabled) work fine for me now. Hope that will fix the issue for you, too.

@vinsworldcom: Could you please check how N++ could use the most recent release of your plugin when installing from the Plugin Manager? That would be great, thanks!

**Comment by vinsworldcom** [comment]
Please manually install version [1.4.5.1](https://github.com/vinsworldcom/nppGitSCM/releases/tag/1.4.5.1).  This will be [default in the next version of N++ Plugin Admin](https://github.com/notepad-plus-plus/nppPluginList/commit/26ae5504589aa66233bca44003dacfced43b0f5f).
