### ISSUE TITLE
Question about Backward Compatibility

### ISSUE THREAD

**Issue by rdipardo** [vinsworldcom/nppGitSCM#7]
I've been [tasked] with documenting the 64-bit plugins that have a hard dependency on the new API [introduced in Notepad++ 8.3].

Could you please confirm that release version [1.4.6.1](https://github.com/vinsworldcom/nppGitSCM/releases/tag/1.4.6.1) was tested for compatibility with N++ 8.2.1 ?

_My apologies if it's already been documented somewhere I haven't looked!_

[tasked]:https://github.com/notepad-plus-plus/nppPluginList/issues/422#issuecomment-1059643501
[introduced in Notepad++ 8.3]: https://community.notepad-plus-plus.org/topic/22492/notepad-v8-3-release

**Comment by vinsworldcom** [comment]
@rdipardo I quickly tested the Blame function of my latest GitSCM with Notepad++ 8.2.1 and it seemed to work fine - no crash.   Other than changing the header files themselves, Blame was the only function that use a Scintilla position call to get the current line to pass to the Git Blame call.

Cheers.

**Comment by rdipardo** [comment]
> I quickly tested the Blame function of my latest GitSCM with Notepad++ 8.2.1 and it seemed to work fine - no crash.

Good enough for me!
Thanks for taking the time to check.
